name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Docker Image Build & Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    # 環境を制限して、デプロイ用の秘密鍵へのアクセスを制限
    environment: production
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/docmost
            ./update.sh

      - name: Deploy Success Discord Notification
        uses: Ilshidur/action-discord@master
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        with:
          args: |
            ✅ **VPSへのデプロイが完了しました**
            リポジトリ: ${{ github.repository }}
            ブランチ: ${{ github.ref }}

      - name: Deploy Failure Discord Notification
        uses: Ilshidur/action-discord@master
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        with:
          args: |
            ❌ **VPSへのデプロイが失敗しました**
            リポジトリ: ${{ github.repository }}
            ブランチ: ${{ github.ref }}'