name: Sync Branch

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Organization Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Git credentials
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/antiagingrecord/docmost.git
          git remote -v | grep upstream || git remote add upstream https://github.com/auxa-m45/docmost.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Checkout branch
        run: |
          git checkout --track upstream/feat/aar_edition || git checkout feat/aar_edition

      - name: Merge upstream changes
        run: |
          git merge --no-edit upstream/feat/aar_edition

      - name: Push changes to origin
        run: |
          git push origin feat/aar_edition
